spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xyz_hotel5?createDatabaseIfNotExist=true
    password: 123123kajun123
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  sql:
    init:
      continue-on-error: true
      mode: always
  #server:
  #  port: 9191



  mail:
    host: smtp.gmail.com
    password: hellosrilanka
    username: chazooltopup@gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000
